### ISSUE TITLE
Change the footer links and put it under the view resume

### ISSUE THREAD

**Issue by hubertle43100** [hubertle43100/minimal-portfolio#1]
### At the bottom of my portfolio I have links

I want the **icons only** and put them under the view resume because it is quick easy access to those and is just quick. Remember to add margins and good spacing for each.

 `Below is what I want to get rid of and replace`
<img width="384" alt="Screenshot 2024-01-10 at 3 37 19 PM" src="https://github.com/hubertle43100/minimal-portfolio/assets/56861838/60c19c6b-1cb6-4081-ad62-a19d083e2384">

**Comment by ghost** [comment]
Hi [hubertle43100](https://github.com/hubertle43100), can I work on this issue?

**Comment by hubertle43100** [comment]
### Yes of course! 🙏 
Thanks for the help `Sathurshanan` appreciate it
