### ISSUE TITLE
Get rid of the fail

### ISSUE THREAD

**Issue by hubertle43100** [hubertle43100/minimal-portfolio#10]
### There is an ❌  on the project

I would just like to resolve it because `it is annoying` to keep seeing the ❌ 

![Screenshot 2024-01-19 at 10 21 22 AM](https://github.com/hubertle43100/minimal-portfolio/assets/56861838/25337d95-28d2-4d24-9c38-aa92cd663a2a)

**Comment by gsteja2307** [comment]
Hi @hubertle43100 ,

I'd be happy to help you fix the workflow. To ensure that I address your requirements accurately, could you please share more details about your expectations for this workflow? Specifically:

1. What is the desired outcome or goal of this workflow?
2. Are there any specific tasks or actions that you want to perform in the workflow?
3. Do you have any preferences regarding the workflow setup, such as build and deployment steps?
4. Are there any specific issues or error messages you've encountered that need to be resolved?

Any additional information you can provide will be valuable in tailoring the workflow to your needs. Feel free to share as much detail as you can, and I'll do my best to assist you effectively.

Looking forward to your response!

**Comment by hubertle43100** [comment]
`Got rid of the YML file `

**Comment by hubertle43100** [comment]
Hello `@gsteja2307`  thanks for the question on solving the problem! I was able to detect the problem and have `got rid of the YML file`
