### ISSUE TITLE
Get rid of the website portfolio project

### ISSUE THREAD

**Issue by hubertle43100** [hubertle43100/minimal-portfolio#26]
In projects, I think it's useless to put the `website's link` there.

**Remove Website portfolio from project**

**Comment by GeorgiosDrivas** [comment]
Hello! I would like to work on this issue.

**Comment by hubertle43100** [comment]
### Thanks for your interest `FiorgosDrivas` 

To give you more context can you just `remove my website project` from displaying on the site? Thanks again!

<img width="1366" alt="Screenshot 2024-02-16 at 1 12 41 PM" src="https://github.com/hubertle43100/minimal-portfolio/assets/56861838/f52f8b33-c954-4f76-ac82-326823d6d098">
