### ISSUE TITLE
Rearrange the project

### ISSUE THREAD

**Issue by hubertle43100** [hubertle43100/minimal-portfolio#4]
### I don't want to see my portfolio website on my portfolio website

> spelling for the portfolio is wrong
<img width="352" alt="Screenshot 2024-01-10 at 3 59 48 PM" src="https://github.com/hubertle43100/minimal-portfolio/assets/56861838/510aa894-12f9-45db-8f5a-a4f584889994">

**Comment by PraisejahOsumgbaBenson** [comment]
Hi, can I work on this issue?

**Comment by praisejahuzoma** [comment]
Hi, can I work on this issue?

**Comment by hubertle43100** [comment]
### Thanks for the help 
For my website
`https://hubertle.online/`

I just want to rearrange the order of projects leaving the "portfolio" in the last slot. Thanks again for the contribution!

**Comment by PraisejahOsumgbaBenson** [comment]
Ok

**Comment by PraisejahOsumgbaBenson** [comment]
Hello, I do have a little problem, so locally from my own computer the projects are way different from the one online.
![localhost_5173_](https://github.com/hubertle43100/minimal-portfolio/assets/58517887/c455bf40-a04a-4182-bff1-9f0ae549f133)
this is what I see in my local environment

And this is what is online
![hubertle online_](https://github.com/hubertle43100/minimal-portfolio/assets/58517887/46c3d647-19d4-445c-be88-e6eddbf6257f)

**Comment by PraisejahOsumgbaBenson** [comment]
I think I have figure it out 
this is what you wanted right
![localhost_5173_ (1)](https://github.com/hubertle43100/minimal-portfolio/assets/58517887/cbcc25c0-c822-474d-99a2-f3699e000ab0)

**Comment by hubertle43100** [comment]
That's perfect! Thanks! 👍

**Comment by PraisejahOsumgbaBenson** [comment]
ok i would create a pull request now

**Comment by PraisejahOsumgbaBenson** [comment]
Hello,
can you check out the pull request or you can give me the access to merge it.

**Comment by hubertle43100** [comment]
### Got the merge done thanks!
